Repository Skatteetaten/vagrant-hashistack, pull requests merged in 2020-10, with the labels that each got.

#369 Bugfix - Make install on mac
  install/mac/Makefile
Labels: skip-changelog

#376 Added host_volume nomad policy
  CHANGELOG.md
  ansible/templates/nomad-policies/write_policy.hcl
Labels: type/enhancement

#383 Feature nomad vault integration
  CHANGELOG.md
  README.md
  ansible/templates/nomad.hcl.j2
Labels: type/enhancement

#391 Release 0.5.0
  CHANGELOG.md
Labels: minor, skip-changelog

#400 Release 0.6.0
  CHANGELOG.md
Labels: minor

#401 Updated section configuration
  CHANGELOG.md
  README.md
Labels: type/documentation

#410 updated build section in README.md
  CHANGELOG.md
  README.md
Labels: type/documentation

#411 Life-cycle diagram
  CHANGELOG.md
  README.md
  docs/image/life-cycle.png
Labels: type/documentation

#409 Added issue and PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/general_issue.md
  .github/pull_request_template.md
  CHANGELOG.md
Labels: theme/ci

#412 Release 0.6.1
  CHANGELOG.md
Labels: patch

#415 Fix CD/CI link
  CHANGELOG.md
  README.md
Labels: type/bug

#418 Updated workflow to test master branch on push
  .github/workflows/on_pr_master.yml
  CHANGELOG.md
  README.md
Labels: theme/ci, type/documentation

#420 Hotfix changelog enforcer
  .github/workflows/on_pr_master.yml
  CHANGELOG.md
Labels: theme/ci, type/bug

#413 Converted to use envfile in workflows
  .github/workflows/on_pr_master.yml
  CHANGELOG.md
Labels: type/enhancement

#422 Added check in workflow job
  .github/workflows/on_pr_master.yml
Labels: skip-changelog, theme/ci

#414 Security policy example
  CHANGELOG.md
  ansible/files/bootstrap/consul/post/020-vault-integration.yml
  ansible/files/bootstrap/consul/post/810-tests.yml
  ansible/files/bootstrap/consul/post/990-write-facts.yml
  ansible/files/bootstrap/consul/post/task/vault-integration.yml
  ansible/files/bootstrap/consul/post/test/vault-integration.yml
  ansible/files/bootstrap/nomad/post/task/acl.yml
  ansible/files/bootstrap/nomad/post/task/vault-integration.yml
  ansible/templates/conf/consul/policies/README.md
  ansible/templates/conf/consul/policies/admin_policy.hcl
  ansible/templates/conf/consul/policies/admin_team_policy.hcl
  ansible/templates/conf/consul/policies/consumer_policy.hcl
  ansible/templates/conf/consul/policies/dev_team_policy.hcl
  ansible/templates/conf/consul/policies/producer_policy.hcl
  ansible/templates/conf/nomad/policies/README.md
  ansible/templates/conf/nomad/policies/consumer_policy.hcl
  ansible/templates/conf/nomad/policies/producer_policy.hcl
Labels: theme/ux, type/enhancement

#425 Update on_pr_master.yml
  .github/workflows/on_pr_master.yml
Labels: skip-changelog

#428 Added test for Vault PKI
  CHANGELOG.md
  ansible/files/bootstrap/vault/post/810-tests.yml
Labels: theme/test

#429 Surpress echo of `build` target
  Makefile
Labels: skip-changelog

#431 Added message when brew is found
  CHANGELOG.md
  install/mac/Makefile
Labels: theme/ux

#433 refactored makefile
  Makefile
Labels: skip-changelog, theme/ux
