Repository Skatteetaten/vagrant-hashistack, pull requests merged in 2020-07, with the labels that each got.

#126 Prerequisites release 0.2.2
  CHANGELOG.md
Labels: patch

#128 authenticate to vagrant cloud
  .github/workflows/on_pr_master.yml
Labels: patch

#129 Update on_pr_master.yml
  .github/workflows/on_pr_master.yml
Labels: patch

#130 Add download link
  README.md
Labels: documentation

#131 Template lifecycle must be a part of template directory.
  template/README.md
  template/vagrant/docs/life-cycle.png
Labels: documentation

#132 Add link to template cloning
  README.md
Labels: documentation

#142 137 make install lack of binaries
  README.md
  install/linux/Makefile
Labels: documentation, enhancement

#146 Nomad ACL bootstrap process
  ansible/bootstrap.yml
  ansible/install.yml
  ansible/nomad_acl_bootstrap.yml
  ansible/templates/nomad-policies/read.policy.hcl
  ansible/templates/nomad-policies/write.policy.hcl
  template/README.md
Labels: enhancement
