Repository Skatteetaten/vagrant-hashistack, pull requests merged in 2020-11, with the labels that each got.

#432 Remove recursors
  CHANGELOG.md
  ansible/templates/conf/consul/010-consul.hcl
Labels: type/bug

#435 release 0.7.0
  CHANGELOG.md
Labels: minor

#440 MacOS ca-certificates
  CHANGELOG.md
  install/mac/Makefile
  install/mac/Vagrantfile
Labels: type/enhancement

#442 Removed shellscripts
  CHANGELOG.md
  ansible/files/bootstrap/example.post_ansible.sh
  ansible/files/bootstrap/example.pre_ansible.sh
Labels: theme/ux

#443 Vault secret management (tokens) bug with override tokens path
  CHANGELOG.md
  ansible/files/bootstrap/consul/post/task/vault-integration.yml
  ansible/files/bootstrap/nomad/post/task/acl.yml
  ansible/files/bootstrap/nomad/post/task/vault-integration.yml
  ansible/templates/conf/consul/policies/README.md
  ansible/templates/conf/nomad/policies/README.md
Labels: type/bug

#444 Prepare patch release 0.7.1
  CHANGELOG.md
Labels: patch

#447 Update software versions
  CHANGELOG.md
  README.md
  ansible/group_vars/all/variables.yml
Labels: type/enhancement

#450 added skip-duplicate runs
  .github/workflows/on_pr_master.yml
  CHANGELOG.md
Labels: theme/ci, type/enhancement

#451 Vault-Nomad integration
  CHANGELOG.md
  README.md
  ansible/files/bootstrap/nomad/post/021-vault-integration.yml
  ansible/files/bootstrap/nomad/post/task/vault-nomad-roles-example.yml
  ansible/files/bootstrap/nomad/pre/010-vault-integration.yml
  ansible/files/bootstrap/nomad/pre/task/configure-nomad.yml
  ansible/templates/conf/nomad/011-integrations.hcl.j2
  ansible/templates/conf/nomad/policies/nomad_server_policy.hcl
  ansible/templates/conf/nomad/roles/nomad-cluster-role.json
  ansible/templates/nomad.service.j2
Labels: type/enhancement

#452 Release 0.8.0
  .github/workflows/on_pr_master.yml
  CHANGELOG.md
Labels: minor

#453 Reverting & fix workflow job
  .github/workflows/on_pr_master.yml
  CHANGELOG.md
Labels: type/bug

#454 Release 0.8.0
  .github/workflows/on_pr_master.yml
  CHANGELOG.md
Labels: minor
