Repository Skatteetaten/vagrant-hashistack, pull requests merged in 2020-06, with the labels that each got.

#22 Release based on tags.
  .env
  .github/workflows/release.yml
Labels: patch

#25 restructure github actions
  .github/workflows/build.yml
  .github/workflows/release.yml
Labels: patch

#26 Add prerequisites for mac-os
  Makefile
  README.md
Labels: documentation, enhancement

#29 Actions actions-test
  .github/workflows/build.yml
Labels: patch

#30 CI/CD through github actions.
  .github/workflows/build.yml
  CHANGELOG.md
  Makefile
  README.md
  ansible/group_vars/all/variables.yml
  packer/cloud-push/bootstrap.sh
  packer/cloud-push/build-push.pkr.hcl
  packer/cloud-push/source.pkr.hcl
  packer/cloud-push/variables.pkr.hcl
Labels: patch

#42 Added contributing.md documentation.
  README.md
  docs/CONTRIBUTING.md
Labels: documentation

#36 Add vault
  ansible/group_vars/all/variables.yml
  ansible/templates/vault.hcl.j2
  ansible/templates/vault.service.j2
  test/Vagrantfile
  test/ansible/playbook.yml
Labels: enhancement

#52 Documentation vault 0.1
  README.md
Labels: documentation

#51 Fix startup issues and update documentation.
  CHANGELOG.md
  README.md
  Vagrantfile
  ansible/ansible.cfg
  ansible/group_vars/all/variables.yml
  ansible/playbook.yml
  ansible/startup.yml
  ansible/templates/consul.hcl.j2
  ansible/templates/consul.service.j2
  ansible/templates/nomad.hcl.j2
  ansible/templates/nomad.service.j2
  ansible/templates/vault.service.j2
  test/Vagrantfile
  test/ansible/ansible.cfg
  vagrant/Vagrantfile
Labels: bug, enhancement

#57 Add linting
  .github/workflows/build.yml
  CHANGELOG.md
Labels: patch

#58 Fix linting issues
  .github/linters/.markdown-lint.yml
  .github/workflows/build.yml
  CHANGELOG.md
  README.md
  docs/CONTRIBUTING.md
Labels: patch

#63 release 0.0.8
  .github/workflows/build.yml
  docs/CONTRIBUTING.md
Labels: patch

#65 Fix changelog-reader
  .github/workflows/build.yml
Labels: patch

#66 upload version changelog
  .github/workflows/build.yml
Labels: patch

#68 Release v0.1.0
  CHANGELOG.md
  README.md
  ansible/startup.yml
  test/ansible/playbook.yml
Labels: minor

#72 Release v0.1.1
  .github/workflows/build.yml
  CHANGELOG.md
Labels: patch

#89 Allow for a "base" use of box without needing to change the defaults of vagrant with virtualbox
  CHANGELOG.md
  README.md
  ansible/playbook.yml
  ansible/templates/update-motd.d/98-hashistack.j2
  ansible/templates/update-motd.d/99-help-text.j2
  packer/Vagrantfile
  packer/source.pkr.hcl
  test/Vagrantfile
Labels: enhancement, patch

#96 Release 0.1.2 - Retry upload to vagrant cloud
  .github/workflows/build.yml
Labels: patch

#98 Stop shell expansion
  CHANGELOG.md
Labels: patch

#93 Dev templates
  Makefile
  packer/source.pkr.hcl
  template/dev/.env
  template/dev/HOWTO.md
  template/dev/Makefile
  template/dev/Vagrantfile
  template/dev/conf/consul/99-override.hcl
  template/dev/conf/nomad/99-override.hcl
  template/dev/conf/vault/99-override.hcl
Labels: documentation, enhancement

#99 push dev template to vagrant-hashistack-template-dev
  .github/workflows/build.yml
  template/dev/README.md
Labels: documentation, enhancement

#111 Release 0.2.0
  .github/workflows/build.yml
  CHANGELOG.md
  README.md
  template/.github/workflows/build.yml
  template/README.md
  test/Makefile
Labels: minor

#112 Release 2.0
  .github/workflows/build.yml
Labels: minor

#113 Update build.yml
  .github/workflows/build.yml
Labels: minor

#121 Release 0.2.1
  CHANGELOG.md
  README.md
  template/README.md
Labels: patch

#122 Consul acl switch
  ansible/bootstrap.yml
  ansible/default_vars.yml
  ansible/install.yml
  ansible/templates/consul-acl.hcl.j2
  docs/life-cycle.png
  packer/Vagrantfile
  template/README.md
  template/test/Makefile
  template/test/vagrant/conf/ansible/playbooks/prestart/0-example.yml
  template/vagrant/conf/ansible/playbooks/prestart/1-acl.yml
Labels: documentation, enhancement
