Repository Skatteetaten/vagrant-hashistack, pull requests merged in 2020-08, with the labels that each got.

#153 run pre-poststart in lexical order. Add examples to show that happening.
  ansible/bootstrap.yml
  template/test/vagrant/conf/ansible/playbooks/poststart/0-example.yml
  template/test/vagrant/conf/ansible/playbooks/poststart/00-poststart-example.yml
  template/test/vagrant/conf/ansible/playbooks/poststart/01-poststart-example.yml
  template/test/vagrant/conf/ansible/playbooks/poststart/02-poststart-example.yml
  template/test/vagrant/conf/ansible/playbooks/prestart/0-example.yml
  template/test/vagrant/conf/ansible/playbooks/prestart/00-prestart-example.yml
  template/test/vagrant/conf/ansible/playbooks/prestart/01-prestart-example.yml
  template/test/vagrant/conf/ansible/playbooks/prestart/02-prestart-example.yml
Labels: bug

#158 Install jq in vagrantbox
  CHANGELOG.md
  packer/bootstrap.sh
Labels: enhancement

#157 Consul secrets engine for vault
  CHANGELOG.md
  ansible/bootstrap.yml
  ansible/install.yml
  ansible/templates/consul-policies/admin.team.policy.hcl
  ansible/templates/consul-policies/dev.team.policy.hcl
  ansible/vault_consul_integration.yml
  template/README.md
Labels: enhancement

#162 extend matrix test and use env variables.
  .github/action/create-env.py
  .github/workflows/on_pr_master.yml
  template/test/Makefile
  test/.env_override
  test/Makefile
Labels: enhancement

#178 Copy ansible dir with all content
  ansible/install.yml
Labels: enhancement

#188 Update install.yml
  ansible/install.yml
Labels: bug

#189 Hashistack version bump
  ansible/group_vars/all/variables.yml
Labels: enhancement

#196 Add ent binaries and toggle via env variable
  CHANGELOG.md
  ansible/bootstrap.yml
  ansible/group_vars/all/variables.yml
  ansible/install.yml
  ansible/roles/hashistack/defaults/main.yml
  ansible/templates/.env_default.j2
Labels: enhancement

#202 template enterprise versions doc
  template/README.md
Labels: documentation

#204 Include custom CA to allow builds behind enterprise firewall
  .github/workflows/on_pr_master.yml
  template/.github/workflows/on_pr_push_master.yml
  template/.gitignore
  template/Makefile
  template/docker/README.md
  template/docker/conf/certificates/.gitignore
  template/docker/conf/certificates/README.md
  template/test_example/docker/Dockerfile
  template/test_example/docker/conf/certificates/.gitignore
  template/test_example/docker/conf/certificates/README.md
Labels: bug, enhancement

#209 Release 0.3.0
  CHANGELOG.md
Labels: minor

#219 Fix template bugs
  CHANGELOG.md
  template/Vagrantfile
  template/dev/ansible/playbook.yml
Labels: bug

#237 Release 0.3.1
  CHANGELOG.md
Labels: patch

#240 GitHub action changelog enforcer
  .github/workflows/on_pr_master.yml
  CHANGELOG.md
Labels: ci, enhancement

#241 Template documentation update
  CHANGELOG.md
  template/LICENSE
  template/README.md
  template/example/README.md
  template/test_example/dev/ansible/01_build_docker_image.yml
Labels: documentation

#244 Changed "Use this template" to button in template/README.md
  CHANGELOG.md
  template/README.md
Labels: documentation, template

#245 fix_cert_missing #239
  CHANGELOG.md
  template/Makefile
Labels: bug

#252 Update on_pr_master.yml
  .github/workflows/on_pr_master.yml
Labels: skip-changelog

#242 "Where to start" doc update
  CHANGELOG.md
  template/README.md
Labels: documentation

#257 Root doc update
  CHANGELOG.md
  README.md
  docs/SystemConfiguration.md
  docs/image/vagrant-hashistack.png
Labels: documentation

#261 CI improvements
  .github/workflows/on_pr_master.yml
  CHANGELOG.md
Labels: ci

#264 Added link to the proxy section
  Makefile
Labels: documentation, skip-changelog, ux

#265 Modified Vgrantfile in template to make use of DRY principles
  CHANGELOG.md
  template/Vagrantfile
  template/Vagrantfile.default
  template/test_example/Vagrantfile
Labels: ci, template, test

#276 Make the bootstrap process idempotent
  CHANGELOG.md
  ansible/bootstrap.yml
  ansible/nomad_acl_bootstrap.yml
  ansible/vault_consul_integration.yml
  ansible/vault_nomad_integration.yml
Labels: bug

#278 Change resources
  CHANGELOG.md
  template/README.md
Labels: documentation

#284 Corrected reference in test/Makefile
  test/Makefile
Labels: skip-changelog

#280 Increase timeout [Task - Archive docker image] #279
  CHANGELOG.md
  template/template_example/dev/ansible/01_build_docker_image.yml
Labels: bug, ci, template

#285 Release 0.4.0
  .github/workflows/on_pr_master.yml
  CHANGELOG.md
  ansible/group_vars/all/variables.yml
  install/.env
Labels: minor

#292 Update on_pr_master.yml
  .github/workflows/on_pr_master.yml
Labels: bug, ci, minor, skip-changelog

#295 Update CHANGELOG.md
  CHANGELOG.md
Labels: bug, ci, minor
