Repository Skatteetaten/vagrant-hashistack, pull requests merged in 2020-09, with the labels that each got.

#303 Fix to circumvent failure when single quote is present in CHANGELOG.md
  .github/action/find-replace.py
  .github/workflows/on_pr_master.yml
  CHANGELOG.md
  template/Makefile
Labels: bug, ci

#311 Modidfied code so as .env file is sourced correctly
  .github/action/create-env.py
  .github/action/find-replace.py
  CHANGELOG.md
  ansible/install.yml
  template/.github/action/create-env.py
Labels: type/bug

#314 Added changelog.md to template
  CHANGELOG.md
  template/CHANGELOG.md
  template/README.md
Labels: type/question

#318 Fixed labels in workflow
  .github/workflows/on_pr_master.yml
Labels: pr/skip-changelog

#313 Linting for TF files + documentation
  .github/linters/.tflint.hcl
  CHANGELOG.md
  docs/CONTRIBUTING.md
  template/.github/linters/.tflint.hcl
  template/README.md
  template/example/vagrant_box_example/main.tf
  template/template_example/example/standalone/main.tf
  template/template_example/example/standalone/variables.tf
  template/template_example/outputs.tf
Labels: type/documentation, type/enhancement

#320 Documentation port collisions
  CHANGELOG.md
  README.md
  template/README.md
Labels: type/documentation

#316 Automatically trigger on_release workflow once release job completes
  .github/workflows/on_pr_master.yml
  CHANGELOG.md
Labels: theme/ci, type/bug

#319 Issue 268 cheatsheet
  CHANGELOG.md
  docs/CHEATSHEET.md
Labels: type/documentation

#328 Release 0.4.1
  .github/workflows/on_pr_master.yml
  CHANGELOG.md
Labels: patch

#333 Release 0.4.2
  CHANGELOG.md
Labels: patch

#340 Vault PKI enabled
  CHANGELOG.md
  README.md
  ansible/bootstrap.yml
  ansible/install.yml
  ansible/templates/.env_default.j2
  ansible/terraform/vault_pki/main.tf
Labels: type/documentation

#348 Release 0.4.3
  CHANGELOG.md
Labels: patch

#349 Consul namespaces feature
  CHANGELOG.md
  ansible/bootstrap.yml
  ansible/tests/consul_acl_test.yml
  ansible/tests/enterprise/consul_namespaces_test.yml
  ansible/tests/enterprise_test.yml
Labels: type/enhancement

#356 Bug fixes for make update-submodule target and help text
  .gitmodules
  CHANGELOG.md
  Makefile
  ansible/templates/update-motd.d/98-hashistack.j2
  ansible/templates/update-motd.d/99-help-text.j2
Labels: type/bug

#351 Add support for installing on Windows
  CHANGELOG.md
  README.md
  install/.env
  install/Makefile
  install/windows/Makefile
  install/windows/Vagrantfile
Labels: type/documentation, type/enhancement

#357 Vault namespaces feature
  CHANGELOG.md
  ansible/tests/enterprise/vault-policy/edu-admin.hcl
  ansible/tests/enterprise/vault-policy/training-admin.hcl
  ansible/tests/enterprise/vault_namespaces_test.yml
  ansible/tests/enterprise_test.yml
Labels: type/enhancement

#360 Updated CONTRIBUTING.md, added plugin directory in vault hcl file
  CHANGELOG.md
  ansible/group_vars/all/variables.yml
  ansible/templates/vault.hcl.j2
  docs/CONTRIBUTING.md
  install/Makefile
Labels: type/documentation, type/enhancement
